name: Test-install distro
on:
  push:
    paths:
      - META6.json
      - lib/**/*.pm6
      - t/*.t
  pull_request:
    paths:
      - META6.json
      - lib/**/*.pm6
      - t/*.t
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test via install
        uses: JJ/raku-test-action@v2
